QUERY = (
"CREATE "
  "(e1:Exit:Sign {id:1, direction: 'up'}),"
  "(e2:Exit:Sign {id:2, direction: 'up'}),"
  "(e3:Exit:Sign {id:3, direction: 'right'}),"
  "(e4:Exit:Sign {id:12, direction: 'up'}),"
  "(s1:Sign {id:4, direction: 'right'}),"
  "(r1:Alarm {id: 5}),"
  "(r2:Alarm {id:6}),"
  "(r3:Alarm {id:7}),"
  "(d1:Delta {id:8, dist: 3}),"
  "(d2:Delta {id:9, dist: 1}),"
  "(d3:Delta {id:10, dist:4}),"
  "(d4:Delta {id:11, dist:5}),"
  "(r1)-[:CONNECTED_TO {cost: 0}]->(d3),"
  "(r2)-[:CONNECTED_TO {cost: 0}]->(d4),"
  "(r3)-[:CONNECTED_TO {cost: 0}]->(d1),"
  "(s1)-[:CONNECTED_TO {cost: 0}]->(d1),"
  "(d1)-[:CONNECTED_TO {cost: 3}]->(e3),"
  "(s1)-[:CONNECTED_TO {cost: 0}]->(d4),"
  "(d4)-[:CONNECTED_TO {cost: 5}]->(e4),"
  "(s1)-[:CONNECTED_TO {cost: 0}]->(d2),"
  "(d2)-[:CONNECTED_TO {cost: 1}]->(e2),"
  "(s1)-[:CONNECTED_TO {cost: 0}]->(d3),"
  "(d3)-[:CONNECTED_TO {cost: 4}]->(e1);"
)